### ISSUE TITLE
Cascadia shakemap missing

### ISSUE THREAD

**Issue by DamonU2** [OpenDRR/pygeoapi#18]

**Comment by jvanulde** [comment]
Added in https://github.com/OpenDRR/pygeoapi/commit/1ab04458c4db135592be1738cc5e74c1212258a4

Waiting on @arashmalekz to implement on Staging.

**Comment by jvanulde** [comment]
Completed: https://geo-api.stage.riskprofiler.ca/collections/opendrr_dsra_sim9p0_cascadiainterfacebestfault_shakemap?lang=en_US

@DamonU2 please add to GitHub pages. Merci!
