### ISSUE TITLE
Pull in patch for pre-generated OpenAPI JSON

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/pygeoapi#4]
As per PR: https://github.com/geopython/pygeoapi/pull/657

The revised workflow would be:

    pygeoapi generate-openapi-document -c opendrr.config.yml -f json > opendrr.openapi.json # this will take awhile
    export PYGEOAPI_CONFIG=/path/to/opendrr.config.yml
    export PYGEOAPI_OPENAPI=/path/to/opendrr.openapi.json
    pygeoapi serve

**Comment by arashmalekz** [comment]
I tested using json schema and it's good. Dev is working fine now. 
https://geo-api.dev.riskprofiler.ca/openapi?f=html

**Comment by jvanulde** [comment]
Excellent @arashmalekz!
