### ISSUE TITLE
pygeoapi too large for AWS Lambda

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/pygeoapi#5]
The pygeoapi binary is over the 250Mb limit for executables in Lambda. As a consequence, there is a cold start as Lambda loads the necessary files. Try reducing the providers to just Elasticsearch.

**Comment by jvanulde** [comment]
Tested locally with just Elasticsearch via Docker. It worked. Although I got errors when trying to build the binary.

**Comment by jvanulde** [comment]
@arashmalekz can this be closed now?

**Comment by arashmalekz** [comment]
Yes, not an issue anymore
